name: build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build and Test
        # `test` firsts triggers `build` which triggers `clean`
        # which in turns triggers `vet` and `fmt` as a series
        # of operations
        run: make test


